theme: jekyll-theme-slate
title: Rejuvenation 13.5 100% Walkthrough
description: In-depth 100% guide for Rejuvenation 13.5 based on BIGJRA's for V13. Still work in progress
github:
  is_project_page: true
